### ISSUE TITLE
Private mode and running detection for Opera

### ISSUE THREAD

**Issue by yanus** [mortenn/BrowserPicker#59]
I've noticed that Browser Picker doesn't give an option to open links in a private window with Opera and also doesn't detect if it's already running.
- The private mode should be easy to solve, as Opera supports the same argument as Chrome (--incognito).
- Opera registers itself with a separate launcher.exe, while the actual process runs as opera.exe (adding the opera.exe manually to Browser Picker is a workaround to enable it to detect it running)

**Comment by mortenn** [comment]
I was working on opera support a little bit, but I've never really enjoyed Opera so didn't end up spending a lot of effort on it.
The fact that they have launcher.exe lead to a bug where a game launcher was picked up as opera, so that at least should be worked out in the latest release.
It should be a fairly simple change to fully support opera, it just wasn't high on my list of priorities at the time.

Hoping I can get some time to work a bit more on this one day soon, but in the mean time, a PR is welcome.

**Comment by mortenn** [comment]
While the PR was merged into the upcoming releases, the way browsers are handled are changing quite a bit in main leading up to 2.0 on .NET 6.
I believe it should work for Opera Stable as is there, though.
