### ISSUE TITLE
Feature Request: Set Default Browser if URL default undefined

### ISSUE THREAD

**Issue by sl4ppy** [mortenn/BrowserPicker#68]
Add the ability to define a certain browser to open all URL's not defined/overridden by a domain in the defaults list

**Comment by kissge** [comment]
This feature would be really great! My use case is like: Open Notion in Notion, open Slack in Slack, and otherwise open in Google Chrome.

**Comment by mortenn** [comment]
Hello, I've just rewritten the configuration part of the app and upgraded it to .NET 8, if you would be so kind as to give [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8495248070/artifacts/1372113556) a try, that'd be great!

**Comment by kissge** [comment]
Great! I'll give it a try...

Off topic: currently I'm experiencing infinite loop of "You must install or update .NET to run this application" 😐 

https://github.com/mortenn/BrowserPicker/assets/4177010/1d60ef8c-2285-48de-91d5-0f76f28893c9

**Comment by kissge** [comment]
I guess this would be THE functionality we wanted, but couldn't enable it. Maybe I should report this somewhere else?


https://github.com/mortenn/BrowserPicker/assets/4177010/f60e95ac-e3b4-4e83-b8f1-24be4cb12de2

**Comment by mortenn** [comment]
ah, the check box for enabling it doesn't work, I didn't test that.
and I only now realize I neglected to hook up the deletion in the DataGrid

**Comment by mortenn** [comment]
please try [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8499547340/artifacts/1372850785)

**Comment by kissge** [comment]
Thanks. This is great work. It's working flawlessly!

// For future readers: apparently Notion.exe necessitates URL rewriting like `https://www.notion.so /${PATH}` to `notion:/${PATH}`, so my use case is impossible

**Comment by mortenn** [comment]
I should be able to add something to support that use case, I am planning on doing the same for teams links eventually :)

**Comment by mortenn** [comment]
This should be implemented now, let me know if something is missing

**Comment by sg2002** [comment]
This does not seem to work for me in the current 2.0.7. The test build posted earlier works though.

**Comment by mortenn** [comment]
does it work in the latest 2.1 pre-release?

**Comment by sg2002** [comment]
No, the latest pre-release does not work either.

**Comment by sg2002** [comment]
Ok, here's what I'm observing, because the behavior is very peculiar.

With the following settings:
- A hostname pattern for youtube.com that opens it in Firefox
- The default browser checkbox is set to Edge

Using 2.1.3 pretest:
- Trying to open either a youtube or any other link results in me still getting the BrowserPicker window
- If I'm opening a link from Telegram, *if* Firefox is already runing it opens links in Firefox, regardless of the settings. I know that BrowserPicker is still involved because I get the "scanning URL" popup

Using the 2.0.0.4 test version from this bug everything works fine. Can it be that it's happening due to some kind of settings incompatibility issue with my old settings breaking the new version? How do I completely delete all BrowserPicker settings to test?

**Comment by mortenn** [comment]
There is an option that controls whether defaults apply when the configured browser is not running, is that enabled?

**Comment by mortenn** [comment]
to delete all settings, simply erase `HKEY_CURRENT_USER\Software\BrowserPicker` from the registry

**Comment by sg2002** [comment]
> There is an option that controls whether defaults apply when the configured browser is not running, is that enabled?
Right, so that is the issue. If that checkbox is not set, even if Firefox is a pattern-only link handler, that link is not going to open in it, even if Firefox is already running.
