### ISSUE TITLE
[FEATURE REQUEST] Hotkeys to Prompt Popup for Browser Selection

### ISSUE THREAD

**Issue by CHE-11** [mortenn/BrowserPicker#75]
Most of the time you just want links to open in a default browser. But sometimes you want them to open elsewhere and only them do you need to select. It would be great if you could set a hot key (ctrl+shift or Win+shift) while selecting a link that launches the BrowserPicker UI to select the browser to open that link in.

**Comment by mortenn** [comment]
Thanks for the idea.

It would be possible to detect modifier key status on startup and change the behaviour, but if you hold a modifier key while clicking a link, that may change the behaviour of the source application.
I know you have to hold ctrl in order to follow links in some apps, like excel - so that can also be a possible concern.

There is also a matter of varying startup times, so there might not be enough time to press the modifier key between clicking the link and the window appearing - in which case we would need either a delay before startup or just respond to the modifier key while the window is shown - in which case just hitting the number key would be just as quick?

I'll leave this issue open for further input, but don't expect I'll be looking at this any time soon unless I get a PR.

**Comment by CHE-11** [comment]
I took this idea from [BrowserTamer](https://www.aloneguid.uk/projects/bt/). They allow for modifier keys but it is closed source and pretty buggy. Not nearly as stable as this.

**Comment by mortenn** [comment]
I have added a short circuit that skips the detection and just shows the choices if the alt key is held down while the window is opening. you may test it out in [this build](https://github.com/mortenn/BrowserPicker/actions/runs/8495248070/artifacts/1372113556)

**Comment by mortenn** [comment]
This feature is included in 2.0.2
