### ISSUE TITLE
Right click option in browser to open in other browsers.

### ISSUE THREAD

**Issue by Uricorn** [mortenn/BrowserPicker#8]
When right clicking on a link in a browser it should have the option "Open link in ....". (Navigates to link but in different browser)

When right clicking on any tab/window "Open in .....". (Duplicates current tab/window but in a different browser)

I have a feeling this may require a browser extension, but here's hoping it won't.

**Comment by mortenn** [comment]
It most certainly would require a browser plugin.

**Comment by mortenn** [comment]
http://www.makeuseof.com/tag/choose-browser-open-specific-link-firefox-extension/
https://chrome.google.com/webstore/detail/open-with-external-applic/hccmhjmmfdfncbfpogafcbpaebclgjcp

Couldn't find anything as good for IE, but this will let you open your current page in another browser:
http://www.winhelponline.com/blog/ie-extension-open-web-page-different-browser/

As this issue is out of scope for this app, I'm going to close it.
I will accept PRs adding plugins for various browsers though, should someone want to integrate that here.
